# Generated by Django 2.2 on 2021-08-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh2app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
